spring.application.name=siw-site-underwear
# Configurazione Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/site-underwear
spring.datasource.username=postgres
spring.datasource.password=Redbull24*
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA/Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurazione Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configurazione Server
server.port=8080